-- 코드를 입력하세요
# SELECT 
#     MONTH(A.START_DATE),
#     A.CAR_ID,
#     COUNT(*) AS RECORDS
# FROM (
#     SELECT 
#         HISTORY_ID,
#         CAR_ID,
#         CASE
#             WHEN START_DATE LIKE '2022-08%' THEN 8
#             WHEN START_DATE LIKE '2022-09%' THEN 9
#             WHEN START_DATE LIKE '2022-10%' THEN 10
#         END AS MONTH
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE BETWEEN '2022-08-01 00:00:00' AND '2022-10-31 23:59:59') AS A
# INNER
# JOIN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE BETWEEN '2022-08-01 00:00:00' AND '2022-10-31 23:59:59'
#     GROUP BY CAR_ID
#     HAVING COUNT(*) >= 5) AS B
# ON A.CAR_ID = B.CAR_ID
# GROUP BY A.CAR_ID, MONTH
# HAVING RECORDS > 0
# ORDER BY MONTH, A.CAR_ID DESC

SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5)
GROUP BY 
    MONTH, CAR_ID
ORDER BY 
    MONTH, CAR_ID DESC